default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: rails_apps
  password: <%= ENV['RAILS_APP_DATABASE_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: linkedin_development

test:
  <<: *default
  database: linkedin_test