default: &default
  adapter: mysql2
  username: rails_repos
  password: password
  host: localhost
  pool: 5

development:
  <<: *default
  database: stackoverflow_development

test:
  <<: *default
  database: stackoverflow_test